### PR TITLE
fixed: `HcfMiddleware` generates fewer links than requested. Solved #58

### PR DESCRIPTION
**Pull request by starrify**
solves #58

### CODE REVIEW

**Comment by nramirezuy** [comment]
That change is equivalent the same as `enumerate(<iterator>, start=1)`.

**Comment by starrify** [comment]
@nramirezuy Have you ever noticed this additional argument `mincount=self.hs_max_links`? :(

**Comment by nyov** [comment]
What's the verdict on this one?
Is the hcf middleware still in use, should this be merged before the project gets broken up?

**Comment by redapple** [comment]
`HcfMiddleware` as it is in scrapylib 1.7.0 is still used, at least at Scrapinghub.
I'll move the middleware to its own repo.
And will ask for the PRs to be moved to there (or will propose the changes myself for authors to review)

**Comment by redapple** [comment]
@starrify , would you mind re-opening this PR against https://github.com/scrapy-plugins/scrapy-hcf ?
Thanks.
We're deprecating scrapylib so I'm closing this one here.

**Pull request closed without merging**
