### PR TITLE
proposed deprecation and merge of  scrapinghub/scmongo

### PR DESCRIPTION
**Pull request by nyov**
I believe this project might escape some bitrot by inclusion into scrapylib.

Since there are so many different scrapy+mongodb projects around now, I thought a rename might be in order but feel free to ignore/change the last commit.

### CODE REVIEW

**Comment by nyov** [comment]
Closing, because outdated again :C 
This probably would go into scrapy-plugins as a project now instead of getting merged here.

Is still missing that last touch (opening the connection in open_spider and closing it in close_spider, as kmike noted) as well. dang, sorry.

**Comment by dangra** [comment]
scrapy-plugins is the way to go. well decided!

**Comment by nyov** [comment]
thanks.

And a Project Request? (Sorry to abuse the dead thread)
Because I would love to see scrapy-independent HTTP caches.

Sadly I have yet to find a perfect extensible and hackable application proxy not geared to reverse caching. Polipo, Privoxy, Squid, mitmproxy, Zorp, ... none look quite right to me :(

I think a standalone proxy with scrapy's httpcache plus modular extension support could be amazing (and keeping it embeddable as well, it would be an elsewhere reuseable DownloaderMiddlewares system).

I could envision extensions for anything from adblocking, privoxy-filter rules, https certificate checking / safebrowsing to tiered caching, memento/google cache lookups and more.

And with a bigger userbase, more contributors, everyone would benefit?

**Comment by barraponto** [comment]
@nyov as long as it still comes with scrapy, i'm ok with the split.
i would totally miss the httpcache, it is my favorite feature of scrapy.

**Pull request closed without merging**
